name: unit_tests

on: 
  push:
    branches:
      - main
    tags: "*"
  pull_request:

env:
  # keep the depot directly in the repository for the cache
  JULIA_DEPOT_PATH: './.julia'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v2
        with:
          version: "1.10"

      - name: Instantiate
        run: |
          rm Manifest.toml || echo "no Manifest.toml found"
          julia --project=./ -e 'import Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/ComputableDAGs/registry.git")); Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/JuliaRegistries/General"));'
          julia --project=./ -e 'using Pkg; Pkg.add(url="https://github.com/QEDjl-project/QEDprocesses.jl/"); Pkg.add(url="https://github.com/QEDjl-project/QEDbase.jl/")'
          julia --project=./ -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project=./ -t 4 -e 'using Pkg; Pkg.test()' -O0
